name: cut3r-slam
channels:
  - pytorch
  - nvidia
  - https://mirrors.bfsu.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/r
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - cairo=1.16.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - dav1d=1.2.1
  - expat=2.7.1
  - ffmpeg=4.3
  - filelock=3.17.0
  - fontconfig=2.14.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libavif=1.1.1
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.84.2
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.8
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.7.3
  - networkx=3.4.2
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.17
  - pcre2=10.42
  - pip=25.1
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.11.13
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.3
  - requests=2.32.4
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tbb=2021.8.0
  - tk=8.6.15
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - typing_extensions=4.12.2
  - urllib3=2.5.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.0
      - addict==2.4.0
      - aiofiles==24.1.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - argcomplete==3.6.2
      - asmk==0.1
      - asttokens==3.0.0
      - attrs==25.3.0
      - blinker==1.9.0
      - brotli==1.1.0
      - click==8.2.1
      - colorama==0.4.6
      - colorlog==6.9.0
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.3
      - curope==0.0.0
      - cycler==0.12.1
      - dash==3.2.0
      - decorator==5.2.1
      - einops==0.8.1
      - embreex==2.17.7.post6
      - evo==1.31.1
      - executing==2.2.0
      - faiss-cpu==1.12.0
      - fastapi==0.116.1
      - fastjsonschema==2.21.2
      - ffmpy==0.6.1
      - flask==3.1.2
      - fonttools==4.59.1
      - fsspec==2025.7.0
      - glcontext==3.0.0
      - glfw==2.9.0
      - gradio==5.43.1
      - gradio-client==1.12.1
      - groovy==0.1.2
      - grpcio==1.74.0
      - gsplat==1.4.0
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.8
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - hydra-core==1.3.2
      - imageio==2.37.0
      - imgui==2.0.0
      - importlib-metadata==8.7.0
      - in3d==0.0.1
      - ipython==9.4.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jaxtyping==0.3.2
      - jedi==0.19.2
      - joblib==1.5.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lazy-loader==0.4
      - lietorch==0.3
      - lpips==0.1.4
      - lxml==6.0.1
      - lz4==4.4.4
      - manifold3d==3.2.1
      - mapbox-earcut==1.0.3
      - markdown==3.8.2
      - markdown-it-py==4.0.0
      - mast3r==0.0.1
      - mast3r-slam==0.0.1
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - moderngl==5.12.0
      - moderngl-window==2.4.6
      - msgpack==1.1.1
      - msgspec==0.19.0
      - multipledispatch==1.0.0
      - narwhals==2.1.2
      - natsort==8.4.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - ninja==1.13.0
      - nodeenv==1.9.1
      - numexpr==2.11.0
      - numpy==1.26.4
      - omegaconf==2.3.0
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - orjson==3.11.2
      - packaging==25.0
      - pandas==2.3.2
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.3.8
      - plotly==6.3.0
      - plyfile==1.1.2
      - prompt-toolkit==3.0.51
      - protobuf==6.32.0
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyaml==25.7.0
      - pycollada==0.9.2
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pyglet==2.1.8
      - pyglm==2.8.2
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - pyrealsense2==2.56.5.9235
      - pyrr==0.10.3
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - referencing==0.36.2
      - regex==2025.7.34
      - retrying==1.4.2
      - rich==14.1.0
      - roma==1.5.4
      - rosbags==0.10.11
      - rpds-py==0.27.0
      - rtree==1.4.1
      - ruamel-yaml==0.18.15
      - ruamel-yaml-clib==0.2.12
      - ruff==0.12.10
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - shapely==2.1.1
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.47.2
      - svg-path==7.0
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tifffile==2025.6.11
      - tokenizers==0.21.4
      - tomlkit==0.13.3
      - torchcodec==0.1.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.55.4
      - trimesh==4.7.4
      - typer==0.16.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uvicorn==0.35.0
      - vhacdx==0.0.8.post2
      - viser==1.0.6
      - wadler-lindig==0.1.7
      - wcwidth==0.2.13
      - websockets==15.0.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - xxhash==3.5.0
      - yourdfpy==0.0.58
      - zipp==3.23.0
      - zstandard==0.24.0
prefix: /usr/local/miniconda3/envs/cut3r-slam
